---
- hosts: cloudcontroller
  become: true
  tasks:
    - name: Create job file
      template:
        src: template_opencraft2_no_service.yml.j2
        dest: /home/{{ username }}/job-template.yaml

    - name: Create job directory
      file:
        path: /home/{{ username }}/jobs
        state: directory

    - name: Create job multiple times
      shell: |
        for i in `seq 1 {{ replicas }}`
        do
          cat "/home/{{ username }}/job-template.yaml" | sed "s/\%ITEM/$i/" \
          > "/home/{{ username }}/jobs/job-$i.yaml"
        done

    - name: Create config folder
      ansible.builtin.copy:
        src: configs/
        dest: /home/{{ username }}/configs/

    - name: Create Opencraft2 ConfigMap
      command: >
        kubectl create configmap opencraft2-config --from-file=/home/{{ username }}/configs

    - name: Launch jobs
      command: >
        kubectl apply -f "/home/{{ username }}/jobs"
